# File: .github/workflows/retrain.yaml
name: Retrain Model

permissions:
  contents: write

on:
  workflow_dispatch:
  repository_dispatch:            # New
    types:                       # New
      - monitoring_retrain       # New

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-redentials: true
          fetch-depth: 0

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==1.5.3 numpy==1.23.5 scikit-learn==1.3.2 matplotlib==3.7.2 seaborn==0.12.2 scipy==1.11.4 joblib psycopg2 sqlalchemy  # New (pinned versions)

      - name: Retrain model
        run: python app/main.py

      - name: Commit & push model.pkl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Sync and stash
          git pull --rebase --autostash origin master

          # Remove old model files
          for old in app/model/model.pkl model/model.pkl app/model.pkl; do
            if git ls-files --error-unmatch "$old" > /dev/null 2>&1; then
              git rm "$old"
              git commit -m "Remove old model: $old"
            fi
          done

          # Add new model
          git add -f app/model.pkl

          # Move into correct directory
          if [ -f app/model.pkl ]; then
            mv app/model.pkl app/model/model.pkl
            git add -f app/model/model.pkl
            git rm --cached app/model.pkl || true
            echo "Moved new model to app/model/model.pkl and staged it."
          fi

          # Commit & push if changes exist
          if ! git diff --cached --quiet; then
            git commit -m "Retrained model: app/model/model.pkl"
            git push origin master
          else
            echo "No changes to commit."
          fi

      - name: Trigger built_deploy via GitHub API
        env:
          PAT_TOKEN: ${{ secrets.PUSH_TOKEN }}
          REPO:      ${{ github.repository }}
        run: |
          echo "Dispatching built_deploy.yml on master…"
          response=$(
            curl -s -o /dev/null -w "%{http_code}" \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $PAT_TOKEN" \
              https://api.github.com/repos/$REPO/actions/workflows/built_deploy.yml/dispatches \
              -d '{"ref":"master"}'
          )
          if [ "$response" = "204" ]; then
            echo "✅ built_deploy workflow dispatched!"
          else
            echo "❌ Dispatch failed with HTTP $response"
            exit 1
          fi
